require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe GregsController do

  def mock_greg(stubs={})
    @mock_greg ||= mock_model(Greg, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all gregs as @gregs" do
      Greg.stub(:all) { [mock_greg] }
      get :index
      assigns(:gregs).should eq([mock_greg])
    end
  end

  describe "GET show" do
    it "assigns the requested greg as @greg" do
      Greg.stub(:find).with("37") { mock_greg }
      get :show, :id => "37"
      assigns(:greg).should be(mock_greg)
    end
  end

  describe "GET new" do
    it "assigns a new greg as @greg" do
      Greg.stub(:new) { mock_greg }
      get :new
      assigns(:greg).should be(mock_greg)
    end
  end

  describe "GET edit" do
    it "assigns the requested greg as @greg" do
      Greg.stub(:find).with("37") { mock_greg }
      get :edit, :id => "37"
      assigns(:greg).should be(mock_greg)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created greg as @greg" do
        Greg.stub(:new).with({'these' => 'params'}) { mock_greg(:save => true) }
        post :create, :greg => {'these' => 'params'}
        assigns(:greg).should be(mock_greg)
      end

      it "redirects to the created greg" do
        Greg.stub(:new) { mock_greg(:save => true) }
        post :create, :greg => {}
        response.should redirect_to(greg_url(mock_greg))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved greg as @greg" do
        Greg.stub(:new).with({'these' => 'params'}) { mock_greg(:save => false) }
        post :create, :greg => {'these' => 'params'}
        assigns(:greg).should be(mock_greg)
      end

      it "re-renders the 'new' template" do
        Greg.stub(:new) { mock_greg(:save => false) }
        post :create, :greg => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested greg" do
        Greg.stub(:find).with("37") { mock_greg }
        mock_greg.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :greg => {'these' => 'params'}
      end

      it "assigns the requested greg as @greg" do
        Greg.stub(:find) { mock_greg(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:greg).should be(mock_greg)
      end

      it "redirects to the greg" do
        Greg.stub(:find) { mock_greg(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(greg_url(mock_greg))
      end
    end

    describe "with invalid params" do
      it "assigns the greg as @greg" do
        Greg.stub(:find) { mock_greg(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:greg).should be(mock_greg)
      end

      it "re-renders the 'edit' template" do
        Greg.stub(:find) { mock_greg(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested greg" do
      Greg.stub(:find).with("37") { mock_greg }
      mock_greg.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the gregs list" do
      Greg.stub(:find) { mock_greg }
      delete :destroy, :id => "1"
      response.should redirect_to(gregs_url)
    end
  end

end
